---
title: "combined"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(flexplot)
```

```{r}
combined_resp_data |> 
 arrange(label)

combined_withcar <- combined_resp_data |> 
  left_join(carbon_data, by = "label")
```

```{r}
combined_resp_data <- combined_resp_data |> 
  mutate(year = year(date_time)) |> 
  mutate(yday = yday(date_time)) |> 
  arrange(label,date_time) |> 
  mutate(time = case_when(year == 2023 ~ yday(date_time) - 156, 
                          year == 2024 ~ yday(date_time)- 28 + 90+119)) |> 
  mutate(treatment = factor(treatment)) |> 
  mutate(ftime = factor(time))
```

```{r}
combined_resp_data |> 
  ggplot(aes(ts,flux))+
  geom_point(aes(color = treatment, shape = treatment))+
  stat_smooth(method = "lm", aes(color = treatment), se = F, show.legend = F)+
stat_regline_equation(
    aes(label = paste(after_stat(eq.label), after_stat(rr.label), sep = "~~~~"), color = treatment), show.legend = F)+
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 12),
  strip.text = element_text(size = 10),  # Facet label text
  legend.text = element_text(size = 12),
  legend.title = element_text(size = 14),
  plot.title = element_text(size = 14, face = "bold"))+
  guides(color = guide_legend(title = "Treatment"),
         shape = guide_legend(title = "Treatment"))+
  labs(x = "Soil temperature (°C)",
       y = "Mean flux (μmol/m2-s)",
       title = "Flux vs. temperature")

combined_resp_data |> 
  ggplot(aes(ts, flux)) +
  geom_point(aes(color = treatment, shape = treatment)) +
  stat_smooth(method = "nls", 
              formula = y ~ a * exp(b * x), 
              method.args = list(start = list(a = 1, b = 0.1)), 
              aes(color = treatment), se = F, show.legend = F) +
  stat_regline_equation(
    aes(label = paste(after_stat(eq.label), after_stat(rr.label), sep = "~~~~"), color = treatment), show.legend = F) +
  theme(axis.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        strip.text = element_text(size = 15),  # Facet label text
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 15),
        plot.title = element_text(size = 15, face = "bold")) +
  guides(color = guide_legend(title = "Treatment"),
         shape = guide_legend(title = "Treatment")) +
  labs(x = "Soil temperature (°C)",
       y = "Mean flux (μmol/m2-s)",
       title = "Flux vs. Temperature")
# ggsave(filename = "tempvsflux.jpg",
#        width = 270, # 14.1 x 5.05 in 358 x 256 mm 
#        height = 195,# 
#        units = "mm",
#        dpi = 200,
#        device = "bmp"
# )
```




```{r fig.width= 8, fig.height=4}

combined_resp_data |> 
  mutate(md = factor(format(combined_resp_data$date_time, format = "%Y-%m-%d"))) |> 
  group_by(md,treatment) |> 
  summarise(mean_flux = mean(flux, na.rm = T)) |> 
  ggplot(aes(md, mean_flux, group = treatment, color = treatment))+
  geom_line(size = 1.5)+
  geom_point(size = 1.5)+
   theme(axis.title = element_text(size = 17),
          axis.text = element_text(size = 17),
          legend.text = element_text(size = 17),
          legend.title = element_text(size = 17),
          axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5),
          panel.grid.major = element_line(color = "gray90"),
          panel.grid.minor = element_blank(),
         legend.position = "top")+
  labs(x = "Sampling Date", y = "Flux")+
  guides(color = guide_legend(title = "Treatment"))

# ggsave(filename = "combined_timeseries.jpg",
#        width = 270, # 14.1 x 5.05 in 358 x 256 mm 
#        height = 195,# 
#        units = "mm",
#        dpi = 200,
#        device = "bmp"
# )


combined_resp_data |> 
  mutate(date = date(date_time),
         year = year(date_time)) |> 
  group_by(date,treatment) |> 
  summarise(mean_flux = mean(flux, na.rm = T)) |> 
  ggplot(aes(date, mean_flux, group = treatment, color = treatment))+
  geom_line(aes(color = treatment))+
  geom_point()+
  scale_x_date(breaks = waiver(), date_labels = "%b %Y")
```

```{r}
library(zoo)
#install.packages("xts")
library(xts)
resp_zoo <- zoo(combined_resp_data$flux, order.by = combined_resp_data$date_time)
resp_xts <- xts(x = combined_resp_data[3:5],
                order.by = combined_resp_data$date_time)
print(resp_xts)
resp_xts_m <- to.monthly(resp_xts$flux)
resp_xts_d <- to.daily(resp_xts$flux)
monthly_avg <- apply.monthly(resp_xts, colMeans, na.rm = TRUE)
plot(resp_xts_m, 
     col = c("blue", "green", "red","purple"),  # Colors for the lines
     lwd = 2,  # Line width
     main = "Time Series Data", 
     ylab = "Values", 
     xlab = "Date")
plot(resp_xts_m, col = c("red", "green", "blue", "purple"), grid.ticks.on = "days", major.ticks = "days", grid.col = "lightgrey")


```



```{r}
combined_resp_data |> 
  ggplot(aes(ts,flux))+
  geom_point(aes(color = treatment, shape = treatment), size = 1.5, alpha = 1)+
  geom_smooth(method = lm,se = T)+
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(size = 10),
  strip.text = element_text(size = 10),  # Facet label text
  legend.text = element_text(size = 10),
  legend.title = element_text(size = 12),
  plot.title = element_text(size = 14, face = "bold"))+
  theme_classic()+
  labs(x = "Soil temperature (°C)",
       y = "Mean Flux (μmol/m2-s)",
       title = "Soil temperature vs. Flux")
model <- lm(flux~ts, data = combined_resp_data)
rsq <- summary(model)$r.squared
pred <- predict(model)
rmse <- rmse(combined_resp_data$flux, pred)
nrmse_sd <- rmse/sd(combined_resp_data$flux)

# ggsave(filename = "tempvsflux.jpg",
#        width = 270, # 14.1 x 5.05 in 358 x 256 mm 
#        height = 195,# 
#        units = "mm",
#        dpi = 200,
#        device = "bmp"
# )
```

```{r}
combined_withcar <- combined_withcar |> 
  mutate(treatment = factor(treatment))
```

GLMM on the combined data
```{r}
lmm1<- lmer(flux ~ treatment+swc+ts + (1|label) +(1|ftime) , data = combined_withcar)
summary(lmm1)

visualize(lmm1,
          formula = flux~treatment,
          plot = "model")


lmm2 <- lmer(flux ~ treatment+swc+ts+total_c_percent + (1|label)+(1|ftime), data = combined_withcar)

added.plot(flux ~ swc+ts, data = combined_withcar)

```
dataset combined with carbon data
```{r}
combined_withcar |> 
  ggplot(aes(total_c_percent, total_n_percent))+
  geom_point()
```

```{r}
resp_normalized <- combined_withcar |> 
  mutate(cn_ratio =  total_c_percent/total_n_percent) 
```

```{r}
resp_normalized |> 
  filter(year(date_time) == 2024) |> 
  mutate(date = date(date_time),
         year = year(date_time)) |> 
  group_by(date,treatment) |> 
  summarise(mean_flux_normalised = mean(flux_normalised, na.rm = T)) |> 
  ggplot(aes(date, mean_flux_normalised, group = treatment, color = treatment))+
  geom_line(aes(color = treatment))+
  geom_point()+
  scale_x_date(breaks = waiver(), date_labels = "%b %Y")
```


Calculation of carbon stock

```{r}
resp_finalized <- resp_normalized |> 
  mutate(
    flux_mgco2 = (flux*44.01)/10^3, 
    root_mass_g = root_density*202.6829916,
    c_stock_kgC_m2 = total_c_percent*bulk_density*10*0.1, 
    flux_mgco2_kgc = flux_mgco2/(c_stock_kgC_m2),
    porosity = (1 - bulk_density/2.65),
    wfps = (swc/porosity)*100) |> 
    dplyr::select(!flux_mgco2)

#write.csv(resp_finalized,"Data/resp_finalized.csv")
```

```{r}
resp_finalized |> 
  filter(!flux > 6) |> 
  ggplot(aes(flux,flux_mgco2_kgc))+
  geom_point(aes(color = treatment))+
  geom_smooth(method = "lm", aes(color = treatment), se = F)+
  stat_regline_equation(
    aes(label = paste(after_stat(eq.label), after_stat(rr.label), sep = "~~~~"), color = treatment), show.legend = F) +
   theme(axis.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        strip.text = element_text(size = 15),  # Facet label text
        legend.text = element_text(size = 13),
        legend.title = element_text(size = 15),
        plot.title = element_text(size = 15, face = "bold"),
        legend.position = "top") +
  guides(color = guide_legend(title = "Treatment"),
         shape = guide_legend(title = "Treatment")) +
  labs(x = "Mean flux (μmol/m2-s)",
       y = "Standardized flux (mgCO2/kgC-s)",
       title = "Standardized with soil carbon(kgC) and rootmass(g)"
  )
#ggsave("Output/fluxvsstdflux.jpg")
```
https://cran.r-project.org/web/packages/multilevelTools/vignettes/lmer-vignette.html - Important blog on model diagnostics. 


```{r}

resp_finalized |> 
  filter(wfps > 0) |> 
  mutate(ts_binned = cut_interval(ts,3)) |> 
  #mutate(month_yr = format(date_time, "%Y-%m")) |> 
  ggplot(aes(wfps,flux_mgco2_kgc))+
  geom_point(aes(color = treatment))+
  geom_smooth(method = "lm", se = F,aes(colour = treatment))
```

```{r}
year_1 <- resp_finalized |> 
  filter(year == 2023) |> 
  filter(!wfps <0.01)
year_2 <- resp_finalized |> 
  filter(year == 2024)
resp_x <- resp_finalized |> 
  filter(!wfps < 0.01)
lmm_y1 <- lmer(flux_mgco2_kgc ~ treatment + wfps + ts + (1|label) , data = resp_x)
summary(lmm_y1)
Anova(lmm_y1, type = 3)

lmm_y2 <- lmer(flux_mgco2_kgc ~ treatment + wfps + ts + (1|label) , data = year_2)
summary(lmm_y2)
Anova(lmm_y2,type = 3)

library(JWileymisc)
library(multilevelTools)
md <- modelDiagnostics(lmm1, ev.perc = .001)
plot(md, ask = FALSE, ncol = 2, nrow = 3)
```


```{r}
library(flexplot)
visualize(lmm_y1, formula = flux_mgco2_kgc ~ ts|wfps, sample = 25)
```

```{r}
visualize(lmm_y2, formula = flux_mgco2_kgc ~ wfps|ts, sample = 25)
```

