---
title: "new_data"
format: html
editor: visual
---
Some time entries in this new dataset was in 12-hour format whereas the rest were in 24-hour format, making things complicated. Code on line 52 fixes this issue. Also, I think there were some issues with the timezone which has been taken care of in line 56 and 57 (update - lines 56,57 wern't really necessary.)
```{r}
library(tidyverse)
library(readxl)
library(hms)
library(janitor)

new_data <- read_excel("../Data/Abney_data.xlsx") |> 
  clean_names()

clean_data <- new_data |> 
  filter(!if_all(everything(),is.na)) |> 
  dplyr::select(c("label","rep","time","flux","swc","ts","date","treatment")) 


# converting time column so that it has just the time, and merging that into the date column to create a datetime column
clean_data$datetime <- clean_data$date+(clean_data$time - as.POSIXct(trunc(clean_data$time, units = "days")))
clean_data <- clean_data |> 
  dplyr::select(!time) |> 
  mutate(day = day(datetime),
         month = (month(datetime)),
         time = as_hms(datetime),
         label = factor(label),
  ) |> 
  mutate(treatment = case_when( label %in% c(1,8,12,20,23) ~ "Disturbance",
                                label %in% c(3,10,14,17,24,2,9,11,19,25) ~ "NPK",
                                label %in% c(4,7,15,16,22) ~ "Control", 
                                label %in% c(5,6,13,18,21) ~ "NPK+Disturbance",
                                .default = "Outside_treatments"
    )) 
new_final <-
  clean_data |> 
  group_by(label,date,treatment) |> 
  summarise(flux = mean(flux, na.rm = T),
            swc = mean(swc, na.rm = T),
            ts = mean(ts, na.rm = T),
            datetime = mean(datetime, na.rm = T),
            .groups = "drop"
            ) |> 
  ungroup() 
clean_data |> 
  filter(flux>10)

new_final <- new_final |>
  rename(c("datetime"= "date_time"))|> 
  dplyr::select(-date) 
new_final <- new_final |> 
  mutate(date_time = parse_date_time(date_time, 
                                    orders = c("Ymd HMS", "Ymd I:MSp", "Ymd IMSp")))

new_final1 <- new_final |> mutate(date_time = force_tz(date_time, "America/New_York"))
resp_final_comb <- resp_final_comb |> mutate(date_time = force_tz(date_time, "America/New_York"))

combined_resp_data <- new_final1 |> 
  rbind(resp_final_comb) 


#write_csv(combined_resp_data,"../Data/combined.csv")

```



```{r}
carbon_data <- read_csv("../Data/soil_carbon.csv") |> 
  clean_names() |> 
  dplyr::select(c(label,total_c_percent,total_n_percent,replicate, bulk_density, root_density))

carbon_data <- carbon_data |> 
  group_by(label,bulk_density,root_density) |> 
  summarise(total_c_percent = mean(total_c_percent),
            total_n_percent = mean(total_n_percent)) |> 
  mutate(label = factor(label))
```

```{r}
read_csv("../Data/resp_finalized.csv")
```

